# Uses enviromnent variables for minio creds, export MINIO_USER_BASE64 and MINIO_PASSWORD_BASE_64 with base64 encoded values then run with 
#   envsubst < minio.yaml | kubectl apply -f -
apiVersion: v1
kind: Namespace
metadata:
  name: minio-ns
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
  namespace: minio-ns
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-creds
  namespace: minio-ns
type: Opaque
data:
  username: ${MINIO_USER_BASE64}
  password: ${MINIO_PASSWORD_BASE64}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-local
  namespace: minio-ns
spec:
  replicas : 1
  selector:
    matchLabels:
      app: minio-local
  template:
    metadata:
      labels:
        app: minio-local
    spec:
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: minio-pvc
      containers:
      - name: minio-container
        volumeMounts:
        - name: data 
          mountPath: "/data"
        image: quay.io/minio/minio:latest
        args:
        - server
        - /data
        - --console-address 
        - :9001

        env:
        - name: MINIO_ROOT_USER
          valueFrom:
            secretKeyRef:
              name: minio-creds
              key: username
               
        - name: MINIO_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: minio-creds
              key: password
        ports:
        - containerPort: 9000
         
        - containerPort: 9001
      
---

apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: minio-ns
spec:
  selector:
    app:  minio-local
  ports:
  - name: api
    port: 9000
    targetPort: 9000
  - name: web
    port: 9001
    targetPort: 9001
   

  type: LoadBalancer

