apiVersion: apps/v1
kind: Deployment
metadata:
  name: codeserver
  namespace: spark-ns
spec:
  selector:
    matchLabels:
      app: codeserver
  template:
    metadata:
      labels:
        app: codeserver
    spec:
      containers:
      - name: codeserver
        image: gcdotd/do-nothing-codeserver:v1.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service

metadata:
  name: codeserver-svc
  namespace: spark-ns
spec:
  type: ClusterIP
  selector:
    app: codeserver
  ports:
  - port: 8086
    targetPort: 80

